spring:
  application:
    name: redbus-app
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/redbus
    username: redbus
    password: redbus123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
  
  elasticsearch:
    uris: http://localhost:9200
  
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.redbus: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

app:
  bus:
    tracking:
      update-interval: 30000 # 30 seconds
  payment:
    gateway:
      enabled: false # Set to true for production
